#!/usr/bin/env python3

from PyQt5.QtWidgets import QtApplication
from model import Model

class Application(QApplication):
    def __init__(self, sys_argv):
        super().__init__()
        self._model = Model()


        # Set up-timers.
        dataplot_timer = # calls view's data plotting method
        
        biofeedback_timer = # calls controller's biofeedback method