#!/usr/bin/env python3

from PyQt5.QtWidgets import QMainWindow, QWidget


class view(QMainWindow):
    
    def __init__(self, model, controller):
        super().__init__()
        
        self._model = model
        self._controller = controller

    # Display options.
    
    
    # Display breathing signal.    
    def plot_signal(self):
        pass          
    
    
    # Display biofeedback mapping with current breathing estimate.
    
    
    # Display breathing spectrum.





